### ISSUE TITLE
.github

### ISSUE THREAD

**Issue by davipatury** [BestVelcro/BR-PROGRAMMERS#1]
O repositório deveria ter uma pasta `.github` (pasta com `CONTRIBUTING.md`, `ISSUE_TEMPLATE.md` e `PULL_REQUEST_TEMPLATE.md`) para facilitar o controle do repositório.

- Sugestão: o repositório ter uma pasta para cada linguagem e dentro de cada pasta de uma language teria uma pasta para determinado framework.

**Comment by kaikecarlos** [comment]
Pasta Adicionada
